name: IOS build .ipa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter  
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Flutter packages
        run: flutter pub get
      
      - name: Test
        run: flutter test

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Publish iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: build/ios/iphoneos/Runner.app